name: bundle-release-gds-way

on:
  push:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: add-cloudfoundry-repository
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        
      - name: install-system-dependencies
        run: |        
          sudo apt-get update

          sudo apt-get install -y ruby
          sudo apt-get install -y nodejs
          sudo apt-get install -y cf7-cli
          
          sudo gem install bundler:1.17.2

      - name: bundle-gds-way
        run: |          
          bundle install --without development
          bundle exec middleman build

      - name: deploy-to-paas
        env:
          CF_USERNAME: ${{ secrets.CF_EMAIL }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
        run: | 
          cf api https://api.cloud.service.gov.uk 
          cf auth
          cf target -o gds-tech-ops -s docs

          cf push -f ./manifest.yml
